# Generated by Django 4.1.2 on 2022-10-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specifications', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_from', models.CharField(max_length=255)),
                ('inner_registration_no', models.CharField(max_length=255)),
                ('bill', models.CharField(max_length=255)),
                ('total_purchase', models.FloatField(default=0)),
                ('total_rent_percentage', models.FloatField(default=0)),
                ('total_rent_currency', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nds', models.PositiveIntegerField(default=0)),
                ('rent_percentage', models.FloatField(default=0)),
                ('rent_currency', models.FloatField(default=0)),
                ('delivery_period', models.DateField(default='2000-01-01')),
                ('prepayment', models.BooleanField(default=False)),
                ('bill_income', models.CharField(max_length=255)),
                ('bill_income_complete', models.BooleanField(default=False)),
                ('warehouse_income_date', models.DateField(default='2000-01-01')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifications.offer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
        ),
    ]
