# Generated by Django 4.1.2 on 2022-10-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify_no', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('WORK', 'В работе'), ('WATCH', 'На согласовании'), ('SPEC', 'Спефицикация согласована'), ('TS', 'Выдано ТЗ'), ('AU', 'Аукцион размещен'), ('BUY', 'Процесс закупки'), ('POST', 'Доставка'), ('BILL', 'Оплата произведена'), ('CLOSE', 'Закрыт'), ('REJ', 'Не состоялся')], max_length=8)),
                ('company_name', models.CharField(max_length=255)),
                ('company_inn', models.CharField(max_length=255)),
                ('company_city', models.CharField(max_length=255)),
                ('company_region', models.CharField(max_length=255)),
                ('company_children_per_class', models.PositiveIntegerField(default=0)),
                ('project_reg_no', models.CharField(max_length=255)),
                ('partner_discount', models.PositiveIntegerField(default=0)),
                ('nds', models.BooleanField(default=False)),
                ('str_by_order', models.BooleanField(default=False)),
                ('link', models.BooleanField(default=False)),
                ('country', models.BooleanField(default=False)),
                ('description', models.BooleanField(default=False)),
                ('description_tech', models.BooleanField(default=False)),
                ('description_add', models.BooleanField(default=False)),
                ('total_requests', models.FloatField(default=0)),
                ('total_offers', models.FloatField(default=0)),
                ('total_partner', models.FloatField(default=0)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('delivery_period', models.DateField(default='2000-01-01')),
                ('contract', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created_by', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.partnerguide')),
                ('specification_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.specificationguide')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diller_fio', models.CharField(max_length=255)),
                ('diller', models.CharField(max_length=255)),
                ('auction_price', models.FloatField(default=0)),
                ('auction_date', models.DateField(default='2000-01-01')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('announcement_date', models.DateField(default='2000-01-01')),
                ('auction_no', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
