# Generated by Django 4.1.2 on 2022-10-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partner_discount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='specification_guide',
        ),
    ]
