# Generated by Django 4.1.2 on 2022-11-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_partner_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company_children_per_class',
            new_name='company_children',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_reg_no',
            new_name='reg_no',
        ),
    ]
