# Generated by Django 4.1.2 on 2022-11-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_company_children_per_class_project_company_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='identify_no',
        ),
    ]
