# Generated by Django 4.1.2 on 2022-11-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='country',
            new_name='option_country',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='option_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_add',
            new_name='option_description_add',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_tech',
            new_name='option_description_tech',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='option_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='str_by_order',
            new_name='option_str_by_order',
        ),
    ]
