# Generated by Django 4.1.2 on 2022-11-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_country_project_option_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_offers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_partner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_requests',
        ),
    ]
