# Generated by Django 4.1.2 on 2022-11-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_total_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='option_country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='option_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='option_description_add',
        ),
        migrations.RemoveField(
            model_name='project',
            name='option_description_tech',
        ),
        migrations.RemoveField(
            model_name='project',
            name='option_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='option_str_by_order',
        ),
    ]
