version: '1'

networks:
    localdev:

services:
    db:
        image: postgres:14.6-alpine
        environment:
            POSTGRES_DB: omsk_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - ./.data:/var/lib/postgresql/data/
        networks:
            - localdev

    
    backend:
        build:
            context: ./backend
        working_dir: /app
        command:
            python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend/:/app
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - ./.env
        networks:
            - localdev


    frontend:
        build:
            context: ./frontend
        working_dir: /app
        ports:
            - 5173:5173
        volumes:
            - ./frontend/:/app
        depends_on:
            - backend
        networks:
            - localdev