# Generated by Django 4.1.2 on 2022-11-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='total',
        ),
        migrations.RemoveField(
            model_name='request',
            name='total',
        ),
    ]
