name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Stop and remove containers, networks
        run: docker compose down
      - name: Remove unused data
        run: docker system prune -a -f
      - name: Start containers
        run: docker compose up -d