name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Create env file from gh secrets
        run: |
          touch backend/.env
          echo "${{ secrets.ENV_FILE }}" >> backend/.env

      - name: Stop and remove containers, networks
        run: docker compose down

      - name: Start containers
        run: docker compose up -d