name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch backend/.env
          echo "${{ secrets.DEBUG }}" > backend/.env
          echo "${{ secrets.ALLOWED_HOSTS }}" > backend/.env
          echo "${{ secrets.CORS_ALLOWED_ORIGINS }}" > backend/.env
          echo "${{ secrets.SECRET_KEY }}" > backend/.env
          echo "${{ secrets.POSTGRES_DB }}" > backend/.env
          echo "${{ secrets.POSTGRES_USER}}" > backend/.env
          echo "${{ secrets.POSTGRES_PASSWORD }}" > backend/.env
          echo "${{ secrets.POSTGRES_HOST }}" > backend/.env
          echo "${{ secrets.POSTGRES_PORT }}" > backend/.env
          
          touch frontend/.env
          echo "${{ secrets.VITE_BASEURL }}" > frontend/.env
      - name: Stop and remove containers, networks
        run: docker compose down
      - name: Remove unused data
        run: docker system prune -a -f
      - name: Start containers
        run: docker compose up -d