name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Create env file from gh secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > backend/.env
          echo "${{ secrets.ENV_FILE_FRONT }}" > frontend/.env

      - name: Stop and remove containers, networks
        run: docker compose down

      - name: Start containers
        run: docker compose up -d --build

      - name: Make migrations
        run: |
          docker exec -i backend python3 manage.py makemigrations
          docker exec -i backend python3 manage.py migrate